
services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: injection_exercise
    ports:
      - "5432:5432"
    volumes:
      #- postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: injectionexercise_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=injection_exercise;Username=myuser;Password=mypassword


#volumes:
 # postgres_data: